config/routes.rb
Rails.application.routes.draw do
  get '/' => 'todo_list#index'

  post 'todo_list/update' => 'todo_list#update'

  post 'todo_list/create' => 'todo_list#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session 
end

app/controllers/todo_list_controller.rb
class TodoListController < ApplicationController
	def index
		@todo = Todo.all
		@projects = Project.all
		
		respond_to do |format|
			format.html # index.html.erb
			format.json  { render :json => {:todo => @todo, 
											:projects => @projects }}
		end
	end

	def update
		todo = Todo.find(params[:todo_id])
		todo.isCompleted = !todo.isCompleted
		todo.save
		redirect_to action: 'index'
	end

	def create
		Todo.create(text: params[:text], isCompleted: false, project_id: params[:project_id])
		redirect_to action: 'index'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_list_helper.rb
module TodoListHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To-do list</title>
    <%= csrf_meta_tags %>

	<%= stylesheet_link_tag "application", media: "all" %>
	<%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_list/create.html.erb
<h1>TodoList#create</h1>
<p>Find me in app/views/todo_list/create.html.erb</p>

app/views/todo_list/index.html.erb
	<div id="addtaskflex">
		<div id="addtask">
			<h3>НОВАЯ ЗАДАЧА</h3>
			<hr id="delimeter" noshade>
			<%= form_tag(todo_list_create_path, method: "post", id: "form") do %>
			  <%= text_field_tag(:text, nil, placeholder: 'Название задачи...') %>

			  <div id="select">
				  <select name="project_id" id="project_id" style="width:100%;">
					<% @projects.each do |project| %>
						<%= options_for_select([[project["title"], project["id"]]]) %>
					<% end %>
				  </select>
			  </div>

			  <div id="buttons">
				  <a id="hide" href="#"><div id="cancel">ОТМЕНА</div></a>
				  <%= link_to "#", id: "submit" do %>
					  <div id="ok">ОК</div>
				  <% end %>
			  </div>
			<% end %>
		</div>
	</div>
	
	<div id="headline">
		<h1>Задачи</h1>
		<div id="plus">
			<%= image_tag("icons/addTodoIcon.png", :alt => "Новая задача") %>
		</div>
	</div>
	
		

	<div class="container">
	
		<div class="row" id="cards">
			<% @projects.each do |project| %>
				<div class="col-12 col-md-6 col-lg-4">
					<div id="todoCard">
						<h3><%= project["title"] %></h3>
						<hr id="delimeter" noshade>
						<ul>
						  <% @todo.each do |task| %>
							<% if task["project_id"] == project["id"] then %>
								<%= form_tag(todo_list_update_path, method: "post", id: task.id) do %>
									<%= hidden_field_tag 'todo_id', task.id %>
									<% if task.isCompleted == true then %>
										<li><input type="checkbox" id="check" value="<%= task.id %>" checked><span class="<%= task.id %>" id="completed"><%= task.text %></span></li>
									<% else  %>
										<li><input type="checkbox" id="check" value="<%= task.id %>"><span class="<%= task.id %>" id="uncompleted"><%= task.text %></span></li>
									<% end %>
								<% end %>
							<% end %>
						  <% end %>
						</ul>
					</div>
				</div>
			<% end %>
		</div>
	</div>

	

app/views/todo_list/update.html.erb
<h1>TodoList#update</h1>
<p>Find me in app/views/todo_list/update.html.erb</p>